enhancement:
  - head-branch: ['^feature', '^add']

bug:
  - head-branch: ['.*bug.*', '.*fix.*']

maintenance:
  - head-branch: ['.*maintenance.*', '.*migration.*', '.*refactor.*']

version-bump:
  - head-branch: ['^dev-', '^release-', '^[0-9]+\.[0-9]+\.x$']
